export * from './class.controller'
export * from './course.controller'
export * from './department.controller'
export * from './office.controller'
export * from './staffMember.controller'
export * from './staffRole.controller'
export * from './student.controller'
export * from './teacher.controller'
